// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddEdgeReducer from "../add_edge_reducer";
import AddNodeReducer from "../add_node_reducer";
import ClearRabbitHoleReducer from "../clear_rabbit_hole_reducer";
import CreateChatThreadReducer from "../create_chat_thread_reducer";
import CreateRabbitHoleReducer from "../create_rabbit_hole_reducer";
import DeleteChatThreadReducer from "../delete_chat_thread_reducer";
import DeleteRabbitHoleReducer from "../delete_rabbit_hole_reducer";
import RemoveEdgeReducer from "../remove_edge_reducer";
import RemoveNodeReducer from "../remove_node_reducer";
import RenameChatThreadReducer from "../rename_chat_thread_reducer";
import SetClustersReducer from "../set_clusters_reducer";
import SetNodeContentReducer from "../set_node_content_reducer";
import UpdateNodeDataReducer from "../update_node_data_reducer";
import UpdateNodeNotesReducer from "../update_node_notes_reducer";
import UpdateNodePositionReducer from "../update_node_position_reducer";
import UpdateNodeStateReducer from "../update_node_state_reducer";
import UpdateRabbitHoleReducer from "../update_rabbit_hole_reducer";
import UpsertChatMessageReducer from "../upsert_chat_message_reducer";

export type AddEdgeParams = __Infer<typeof AddEdgeReducer>;
export type AddNodeParams = __Infer<typeof AddNodeReducer>;
export type ClearRabbitHoleParams = __Infer<typeof ClearRabbitHoleReducer>;
export type CreateChatThreadParams = __Infer<typeof CreateChatThreadReducer>;
export type CreateRabbitHoleParams = __Infer<typeof CreateRabbitHoleReducer>;
export type DeleteChatThreadParams = __Infer<typeof DeleteChatThreadReducer>;
export type DeleteRabbitHoleParams = __Infer<typeof DeleteRabbitHoleReducer>;
export type RemoveEdgeParams = __Infer<typeof RemoveEdgeReducer>;
export type RemoveNodeParams = __Infer<typeof RemoveNodeReducer>;
export type RenameChatThreadParams = __Infer<typeof RenameChatThreadReducer>;
export type SetClustersParams = __Infer<typeof SetClustersReducer>;
export type SetNodeContentParams = __Infer<typeof SetNodeContentReducer>;
export type UpdateNodeDataParams = __Infer<typeof UpdateNodeDataReducer>;
export type UpdateNodeNotesParams = __Infer<typeof UpdateNodeNotesReducer>;
export type UpdateNodePositionParams = __Infer<typeof UpdateNodePositionReducer>;
export type UpdateNodeStateParams = __Infer<typeof UpdateNodeStateReducer>;
export type UpdateRabbitHoleParams = __Infer<typeof UpdateRabbitHoleReducer>;
export type UpsertChatMessageParams = __Infer<typeof UpsertChatMessageReducer>;

