// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  rabbitHoleId: __t.string(),
  edgeId: __t.string(),
  source: __t.string(),
  target: __t.string(),
  edgeType: __t.string(),
  trust: __t.string(),
  weight: __t.f64(),
  evidence: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
};
