// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  rabbitHoleId: __t.string().name("rabbit_hole_id"),
  label: __t.string(),
  description: __t.option(__t.string()),
  nodeIdsJson: __t.string().name("node_ids_json"),
  color: __t.option(__t.string()),
  centroidJson: __t.option(__t.string()).name("centroid_json"),
});
