// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  rabbitHoleId: __t.string().name("rabbit_hole_id"),
  source: __t.string(),
  target: __t.string(),
  edgeType: __t.string().name("edge_type"),
  trust: __t.string(),
  weight: __t.f64(),
  evidence: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
});
