// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddEdgeReducer from "./add_edge_reducer";
import AddNodeReducer from "./add_node_reducer";
import ClearRabbitHoleReducer from "./clear_rabbit_hole_reducer";
import CreateChatThreadReducer from "./create_chat_thread_reducer";
import CreateRabbitHoleReducer from "./create_rabbit_hole_reducer";
import DeleteChatThreadReducer from "./delete_chat_thread_reducer";
import DeleteRabbitHoleReducer from "./delete_rabbit_hole_reducer";
import RemoveEdgeReducer from "./remove_edge_reducer";
import RemoveNodeReducer from "./remove_node_reducer";
import RenameChatThreadReducer from "./rename_chat_thread_reducer";
import SetClustersReducer from "./set_clusters_reducer";
import SetNodeContentReducer from "./set_node_content_reducer";
import UpdateNodeDataReducer from "./update_node_data_reducer";
import UpdateNodeNotesReducer from "./update_node_notes_reducer";
import UpdateNodePositionReducer from "./update_node_position_reducer";
import UpdateNodeStateReducer from "./update_node_state_reducer";
import UpdateRabbitHoleReducer from "./update_rabbit_hole_reducer";
import UpsertChatMessageReducer from "./upsert_chat_message_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChatMessageRow from "./chat_message_table";
import ChatThreadRow from "./chat_thread_table";
import ClusterRow from "./cluster_table";
import EdgeRow from "./edge_table";
import NodeRow from "./node_table";
import NodeContentRow from "./node_content_table";
import RabbitHoleRow from "./rabbit_hole_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  chat_message: __table({
    name: 'chat_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
      { name: 'seq', algorithm: 'btree', columns: [
        'seq',
      ] },
      { name: 'thread_id', algorithm: 'btree', columns: [
        'threadId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  chat_thread: __table({
    name: 'chat_thread',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
      { name: 'updated_at', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'chat_thread_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatThreadRow),
  cluster: __table({
    name: 'cluster',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
    ],
    constraints: [
      { name: 'cluster_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClusterRow),
  edge: __table({
    name: 'edge',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
    ],
    constraints: [
      { name: 'edge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EdgeRow),
  node: __table({
    name: 'node',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
    ],
    constraints: [
      { name: 'node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NodeRow),
  node_content: __table({
    name: 'node_content',
    indexes: [
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { name: 'rabbit_hole_id', algorithm: 'btree', columns: [
        'rabbitHoleId',
      ] },
    ],
    constraints: [
      { name: 'node_content_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeContentRow),
  rabbit_hole: __table({
    name: 'rabbit_hole',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rabbit_hole_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RabbitHoleRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_edge", AddEdgeReducer),
  __reducerSchema("add_node", AddNodeReducer),
  __reducerSchema("clear_rabbit_hole", ClearRabbitHoleReducer),
  __reducerSchema("create_chat_thread", CreateChatThreadReducer),
  __reducerSchema("create_rabbit_hole", CreateRabbitHoleReducer),
  __reducerSchema("delete_chat_thread", DeleteChatThreadReducer),
  __reducerSchema("delete_rabbit_hole", DeleteRabbitHoleReducer),
  __reducerSchema("remove_edge", RemoveEdgeReducer),
  __reducerSchema("remove_node", RemoveNodeReducer),
  __reducerSchema("rename_chat_thread", RenameChatThreadReducer),
  __reducerSchema("set_clusters", SetClustersReducer),
  __reducerSchema("set_node_content", SetNodeContentReducer),
  __reducerSchema("update_node_data", UpdateNodeDataReducer),
  __reducerSchema("update_node_notes", UpdateNodeNotesReducer),
  __reducerSchema("update_node_position", UpdateNodePositionReducer),
  __reducerSchema("update_node_state", UpdateNodeStateReducer),
  __reducerSchema("update_rabbit_hole", UpdateRabbitHoleReducer),
  __reducerSchema("upsert_chat_message", UpsertChatMessageReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

