// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  rabbitHoleId: __t.string().name("rabbit_hole_id"),
  dataJson: __t.string().name("data_json"),
  state: __t.string(),
  positionX: __t.f64().name("position_x"),
  positionY: __t.f64().name("position_y"),
  clusterId: __t.option(__t.string()).name("cluster_id"),
  scoresJson: __t.string().name("scores_json"),
  addedAt: __t.u64().name("added_at"),
  expandedAt: __t.option(__t.u64()).name("expanded_at"),
  userNotes: __t.option(__t.string()).name("user_notes"),
});
