// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.string(),
  rabbitHoleId: __t.string(),
  threadId: __t.string(),
  seq: __t.u64(),
  role: __t.string(),
  messageJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatThread = __t.object("ChatThread", {
  id: __t.string(),
  rabbitHoleId: __t.string(),
  title: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  nextSeq: __t.u64(),
});
export type ChatThread = __Infer<typeof ChatThread>;

export const Cluster = __t.object("Cluster", {
  id: __t.string(),
  rabbitHoleId: __t.string(),
  label: __t.string(),
  description: __t.option(__t.string()),
  nodeIdsJson: __t.string(),
  color: __t.option(__t.string()),
  centroidJson: __t.option(__t.string()),
});
export type Cluster = __Infer<typeof Cluster>;

export const Edge = __t.object("Edge", {
  id: __t.string(),
  rabbitHoleId: __t.string(),
  source: __t.string(),
  target: __t.string(),
  edgeType: __t.string(),
  trust: __t.string(),
  weight: __t.f64(),
  evidence: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
});
export type Edge = __Infer<typeof Edge>;

export const Node = __t.object("Node", {
  id: __t.string(),
  rabbitHoleId: __t.string(),
  dataJson: __t.string(),
  state: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  clusterId: __t.option(__t.string()),
  scoresJson: __t.string(),
  addedAt: __t.u64(),
  expandedAt: __t.option(__t.u64()),
  userNotes: __t.option(__t.string()),
});
export type Node = __Infer<typeof Node>;

export const NodeContent = __t.object("NodeContent", {
  nodeId: __t.string(),
  rabbitHoleId: __t.string(),
  url: __t.string(),
  content: __t.string(),
  truncated: __t.bool(),
});
export type NodeContent = __Infer<typeof NodeContent>;

export const RabbitHole = __t.object("RabbitHole", {
  id: __t.string(),
  name: __t.string(),
  rootQuery: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type RabbitHole = __Infer<typeof RabbitHole>;

